"""Writes frontend/js/privacy-text.js from docs/PRIVACY.md.

docs/PRIVACY.md is the one text to edit (docs/REVAMP_BRIEF.md section 7 asks for a plain-language privacy page
"and a 'Datenschutz' screen in the parent area that shows the same text"). The frontend has no build step, so
this turns the German and English sections into a small JS file the browser loads. Run it after editing:

    python scripts/sync_privacy.py

tests/test_privacy.py fails if the two ever go out of step.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PRIVACY_FILE = ROOT / "docs" / "PRIVACY.md"
OUTPUT_FILE = ROOT / "frontend" / "js" / "privacy-text.js"
SECTIONS = {"Deutsch": "de", "English": "en"}


def sections(markdown: str) -> dict[str, str]:
    """The text under each "## Deutsch" / "## English" heading, keyed by language code."""
    found, current = {}, None
    for line in markdown.splitlines():
        if line.startswith("## "):
            current = SECTIONS.get(line[3:].strip())
            if current:
                found[current] = []
        elif current:
            found[current].append(line)
    return {code: "\n".join(lines).strip() for code, lines in found.items()}


def privacy_js(markdown: str) -> str:
    return (
        "// Generated by scripts/sync_privacy.py from docs/PRIVACY.md: do not edit this file by hand.\n"
        "window.PRIVACY_TEXT = " + json.dumps(sections(markdown), ensure_ascii=False, indent=2) + ";\n"
    )


def main() -> None:
    OUTPUT_FILE.write_text(privacy_js(PRIVACY_FILE.read_text(encoding="utf-8")), encoding="utf-8")
    print(f"Wrote {OUTPUT_FILE.relative_to(ROOT)} from {PRIVACY_FILE.relative_to(ROOT)}.")


if __name__ == "__main__":
    main()
