"""Writes frontend/js/layouts-data.js from frontend/layouts/*.json.

docs/REVAMP_BRIEF.md section 4.4 asks that the on-screen keyboard, finger zones, and lessons all read
keyboard layouts "from one source", stored as data files (frontend/layouts/*.json). Those .json files are
that one source, and are what a parent or translator would edit to add a new keyboard shape. The frontend
has no build step, though, so it cannot load a plain .json file as a script the way it loads a .js file;
this tiny generator turns the three layout files into the small JS file frontend/js/keyboard.js actually
reads. Run it after editing a file in frontend/layouts/:

    python scripts/sync_layouts.py

tests/test_layouts.py fails if the generated file and the source .json files ever go out of step, the
same way frontend/js/config.js is kept in step with branding.json (see scripts/sync_branding.py).
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LAYOUTS_DIR = ROOT / "frontend" / "layouts"
OUT_FILE = ROOT / "frontend" / "js" / "layouts-data.js"

# Fixed order so the generated file (and the parent's keyboard-shape picker) is stable between runs.
LAYOUT_IDS = ("qwerty", "qwertz", "qwerty_es")


def load_layouts() -> dict:
    return {layout_id: json.loads((LAYOUTS_DIR / f"{layout_id}.json").read_text(encoding="utf-8"))
            for layout_id in LAYOUT_IDS}


def _row_line(row: list) -> str:
    return "[" + ", ".join(json.dumps(key, ensure_ascii=False) for key in row) + "]"


def _rows_block(layout_id: str, rows: list) -> str:
    lines = ",\n".join("    " + _row_line(row) for row in rows)
    return f"  {json.dumps(layout_id)}: [\n{lines}\n  ]"


def layouts_js(layouts: dict) -> str:
    rows_block = ",\n".join(_rows_block(layout_id, data["rows"]) for layout_id, data in layouts.items())
    names_block = ",\n".join(f'  {json.dumps(layout_id)}: {json.dumps(data["name"], ensure_ascii=False)}'
                              for layout_id, data in layouts.items())
    return (
        "// Generated by scripts/sync_layouts.py from frontend/layouts/*.json: do not edit this file by hand.\n"
        "// To add a key or a whole keyboard shape, edit the matching frontend/layouts/<id>.json and run that\n"
        "// script again. Read by frontend/js/keyboard.js, which draws the on-screen keyboard and finger\n"
        "// colours from this same data, so there is only one place that knows what each keyboard looks like.\n"
        f"const KEY_ROWS = {{\n{rows_block}\n}};\n"
        f"const KEYBOARD_NAMES = {{\n{names_block}\n}};\n"
    )


def main() -> None:
    OUT_FILE.write_text(layouts_js(load_layouts()), encoding="utf-8")
    print(f"Wrote {OUT_FILE.relative_to(ROOT)} from frontend/layouts/*.json.")


if __name__ == "__main__":
    main()
