"""Writes frontend/js/config.js from branding.json.

branding.json is the one file to edit (docs/REVAMP_BRIEF.md section 4.7: "put the product name, mascot
name, colours and logo in one file, and read them everywhere from there"). The frontend has no build
step, though, so it cannot load a plain .json file as a script; this tiny generator turns it into the
small JS file the browser actually loads. Run it after editing branding.json:

    python scripts/sync_branding.py

tests/test_branding.py fails if the two ever go out of step, the same way frontend/js/emoji-map.js
and the voice recordings' index.json are kept in step with what generates them.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BRANDING_FILE = ROOT / "branding.json"
CONFIG_FILE = ROOT / "frontend" / "js" / "config.js"


def config_js(branding: dict) -> str:
    lines = [f"  {key}: {json.dumps(value, ensure_ascii=False)}," for key, value in branding.items()]
    return (
        "// Generated by scripts/sync_branding.py from branding.json: do not edit this file by hand.\n"
        "// To change the mascot's name, colours or logo, edit branding.json and run that script again.\n"
        "window.TIPPY_CONFIG = {\n" + "\n".join(lines) + "\n};\n"
    )


def main() -> None:
    branding = json.loads(BRANDING_FILE.read_text(encoding="utf-8"))
    CONFIG_FILE.write_text(config_js(branding), encoding="utf-8")
    print(f"Wrote {CONFIG_FILE.relative_to(ROOT)} from {BRANDING_FILE.name}.")


if __name__ == "__main__":
    main()
