// Generated by scripts/sync_branding.py from branding.json: do not edit this file by hand.
// To change the mascot's name, colours or logo, edit branding.json and run that script again.
window.TIPPY_CONFIG = {
  mascotName: "Tippy",
  mascotColor: "#ff9f43",
  mascotBellyColor: "#ffe9c7",
};
