// Draws Twemoji pictures over the emoji the app already uses, instead of leaving it to the operating
// system's own emoji font. Native emoji look different on every computer (and some are missing outright,
// for example Windows has no flag pictures); Twemoji is one open, colourful set bundled locally so it
// always looks the same and complete. EMOJI_MAP (frontend/js/emoji-map.js, generated by
// scripts/fetch_emoji.py) lists which emoji have a picture; anything not in it is simply left as the
// plain character, so nothing ever breaks if a picture is missing.
//
// The tricky bit: the app itself sometimes reads an element's *text* back out, for example to find which
// button says "🍎" or to count "●" progress dots (see keyboard.js softMiss, basics.js pick, common.js
// T.goalKey). A picture must not break that. So we never remove the emoji character from the page: we
// wrap it in a span, keep the character itself but shrink it to invisible (font-size: 0, see the .twe-txt
// rule in style.css), and draw the picture next to it. `element.textContent` still returns the emoji
// exactly as before; only what the child sees changes.
(function () {
  const map = window.EMOJI_MAP || {};
  const keys = Object.keys(map);
  if (!keys.length) return;
  // Longest first, so a multi-character emoji (a flag is two characters) is matched whole, not in pieces.
  keys.sort((a, b) => b.length - a.length);
  const pattern = new RegExp(keys.map((k) => k.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|"), "g");

  function wrap(emoji) {
    const hidden = document.createElement("span");
    hidden.className = "twe-txt";
    hidden.setAttribute("aria-hidden", "true");
    hidden.textContent = emoji;
    const picture = document.createElement("img");
    picture.className = "twe";
    picture.src = "assets/twemoji/" + map[emoji];
    picture.alt = emoji;
    picture.draggable = false;
    const holder = document.createElement("span");
    holder.className = "twe-wrap";
    holder.append(hidden, picture);
    return holder;
  }

  // Splits one run of text into the pieces a picture can be dropped into: ["some text", <span>, "more text", ...].
  function pieces(text) {
    const out = [];
    let last = 0;
    let match;
    pattern.lastIndex = 0;
    while ((match = pattern.exec(text))) {
      if (match.index > last) out.push(document.createTextNode(text.slice(last, match.index)));
      out.push(wrap(match[0]));
      last = match.index + match[0].length;
    }
    if (last < text.length) out.push(document.createTextNode(text.slice(last)));
    return out;
  }

  function hydrate(node) {
    if (node.nodeType === 3) {                    // a plain text node: swap it for text + picture pieces, if it has emoji
      pattern.lastIndex = 0;
      if (node.parentNode && pattern.test(node.textContent)) node.replaceWith(...pieces(node.textContent));
      return;
    }
    if (node.nodeType !== 1 || node.tagName === "SCRIPT" || node.tagName === "STYLE" || node.classList?.contains("twe-wrap")) return;
    [...node.childNodes].forEach(hydrate);          // copy first: hydrate() below may replace nodes while we are looking at them
  }

  window.hydrateEmoji = hydrate;

  // Every screen swap (setScreen/show), every modal, and every later update (a fresh score, a new letter,
  // a spoken line arriving) all change the page in their own way. Rather than have every one of those
  // remember to ask for pictures, one observer watches the whole app and hydrates whatever changes.
  document.addEventListener("DOMContentLoaded", () => {
    const app = document.getElementById("app") || document.body;
    hydrate(app);
    new MutationObserver((mutations) => {
      for (const m of mutations) {
        if (m.type === "characterData") hydrate(m.target);
        else m.addedNodes.forEach(hydrate);
      }
    }).observe(app, { childList: true, subtree: true, characterData: true });
  });
})();
