// Generated by scripts/sync_layouts.py from frontend/layouts/*.json: do not edit this file by hand.
// To add a key or a whole keyboard shape, edit the matching frontend/layouts/<id>.json and run that
// script again. Read by frontend/js/keyboard.js, which draws the on-screen keyboard and finger
// colours from this same data, so there is only one place that knows what each keyboard looks like.
const KEY_ROWS = {
  "qwerty": [
    ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
    ["A", "S", "D", "F", "G", "H", "J", "K", "L"],
    ["SHIFT", "Z", "X", "C", "V", "B", "N", "M", "BACKSPACE"],
    ["SPACE", "ENTER"]
  ],
  "qwertz": [
    ["Q", "W", "E", "R", "T", "Z", "U", "I", "O", "P", "Ü", "ß"],
    ["A", "S", "D", "F", "G", "H", "J", "K", "L", "Ö", "Ä"],
    ["SHIFT", "Y", "X", "C", "V", "B", "N", "M", "BACKSPACE"],
    ["SPACE", "ENTER"]
  ],
  "qwerty_es": [
    ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
    ["A", "S", "D", "F", "G", "H", "J", "K", "L", "Ñ"],
    ["SHIFT", "Z", "X", "C", "V", "B", "N", "M", "BACKSPACE"],
    ["SPACE", "ENTER"]
  ]
};
const KEYBOARD_NAMES = {
  "qwerty": "QWERTY",
  "qwertz": "QWERTZ",
  "qwerty_es": "QWERTY Ñ"
};
